### ISSUE TITLE
Xcode building is broken in 3.2.2 tag and in the master

### ISSUE THREAD

**Issue by soniccat** [appsquickly/Typhoon#383] opened 2015-07-19 20:26 UTC
Trying to build Typhoon from 3.2.2 tag and from the master (480d90c2437d771) in Xcode I have these errors:

```
While building module 'Typhoon' imported from /Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/TypeConversion/Converters/TyphoonPrimitiveTypeConverter.h:14:
In file included from <module-includes>:1:
/Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/Typhoon.h:25:9: error: include of non-modular header inside framework module 'Typhoon' [-Werror,-Wnon-modular-include-in-framework-module]
#import "TyphoonFactoryDefinition.h"
        ^
While building module 'Typhoon' imported from /Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/TypeConversion/Converters/TyphoonPrimitiveTypeConverter.h:14:
<module-includes>:1:1: error: umbrella header for module 'Typhoon' does not include header '/Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/Vendor/OCLogTemplate/OCLogTemplate.h' [-Werror,-Wincomplete-umbrella]
#import "/Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/Typhoon.h"
^
2 errors generated.
In file included from /Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/TypeConversion/Converters/TyphoonPrimitiveTypeConverter.m:13:
/Users/alexeyglushkov/iPhoneProjects/Typhoon/Source/TypeConversion/Converters/TyphoonPrimitiveTypeConverter.h:14:9: fatal error: could not build module 'Typhoon'
#import "TyphoonTypeConverter.h"
 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

3.2.1 tag is built without mistakes

**Comment by jasperblues** [comment] 2015-07-19 22:55
According to StackOverflow: "A quick fix (but not solving the root cause) is to set the following setting to yes: CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES"

**Comment by soniccat** [comment] 2015-07-20 09:02
I've tried it. But there are three problems in my logs (but the last 2 could be related). The solution fixes only the first one. I just checked out the 3.2.1 tag and created the issue to let you know about the problem.

**Comment by jasperblues** [comment] 2015-07-20 09:04
@soniccat  Thanks for the information. Will investigate and address ASAP. In the meantime please consider using Typhoon from Source of CocoaPods. Sorry for the inconvenience.

**Comment by jasperblues** [comment] 2015-07-25 05:46
Closing as we've found the problem via #387 and will fix shortly.

**Closed by jasperblues** 2015-07-25 05:46 UTC
