### ISSUE TITLE
Missing TyphoonDefinition method in Swift

### ISSUE THREAD

**Issue by mavericksunny** [appsquickly/Typhoon#351] opened 2015-05-17 15:37 UTC
The following method is never available when accessed in a .swift file (importing Typhoon via Objective C Header) :

+ (id)withFactory:(id)factory selector:(SEL)selector parameters:(void (^)(TyphoonMethod *factoryMethod))params configuration:(void(^)(TyphoonFactoryDefinition *definition))configuration;

Although If i access the same method in an Objective-C  .m source file, it is available.

Example:
![screen shot 2015-05-17 at 9 05 59 pm](https://cloud.githubusercontent.com/assets/4373099/7671000/916364c2-fcd8-11e4-9489-985fcebebf12.png)

Two workarounds:
1. Create a separate TyphoonAssembly in Objective-C and import the assembly in the bridging header and use the assembly in the Swift files.
2. Use the use_frameworks! flag in the PodFile, the Typhoon Dynamic Framework will include this method in Swift and allows me to use this method.

So as my application needs to be compatible with iOS 7.0, I cant go for approach 2 so I am stuck with approach 1.

Has anyone else faced this problem?

**Comment by jasperblues** [comment] 2015-05-18 02:00
You can use the trailing closure syntax like this:

http://stackoverflow.com/a/30136684/404201

```swift
public dynamic func motherOfKnights() -> AnyObject {
    return TyphoonDefinition.withClass(MotherOfKnights.self)
}

public dynamic func brandNewBabyKnight() -> AnyObject {
    return TyphoonDefinition.withFactory(self.motherOfKnights(), 
      selector: "makeKnight:") {
        (factoryMethod) in

        factoryMethod.injectParameterWith("Robert")
    }
}
```

**Comment by jasperblues** [comment] 2015-05-18 02:10
Oh, after reading your question again, not sure what is happening there. Will need to investigate.

**Comment by mogol** [comment] 2015-07-20 10:15
I could not reproduce this case, using the latest beta and released Xcode's and Typhoon.

**Comment by mavericksunny** [comment] 2015-07-20 10:16
It seems to be fixed in the latest version.

**Comment by jasperblues** [comment] 2015-07-20 10:17
Thankyou @mogol  and @mavericksunny. I'll close this then.

**Closed by jasperblues** 2015-07-20 10:17 UTC
Labels: bug
