### ISSUE TITLE
(Fixed in Swift 1.2) Some methods (eg initWithNibName:bundle) vtabled in release mode

### ISSUE THREAD

**Issue by jdbunford** [appsquickly/Typhoon#286] opened 2014-12-01 11:34 UTC
Hi

Steps to reproduce:
1) Download the example. 
2) Change the Build Configuartion scheme from 'Debug' to 'Release'
3) Build and Run

Here is a copy of the exception being raised on startup.

2014-12-01 11:29:38.369 PocketForecast[38575:636356] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Method 'initWithNibName:bundle:' has 2 parameters, but 1 was injected. Inject with 'nil' if necessary'

The wrong parameters seem to be being injected into the initialiser...

Could this be a SWIFT closure problem? Strange it only happens in RELEASE builds. 

FYI I am also seeing the same problem with my own SWIFT application using Typhoon both 2.3.0 & 2.3.1

**Comment by mowens** [comment] 2015-02-11 00:24
From Apple bug report:

> Apple Developer Relations10-Feb-2015 12:50 PM

> We believe this issue has been addressed in the latest Xcode 6.3 beta, including iOS 8.3 SDK with Swift 1.2.

> Please test with this release.  If you still have issues, please include any relevant logs or information that could help us investigate.

> This is a pre-release version of the complete Xcode developer toolset for Mac, iPhone, iPad, and Apple Watch. This release requires OS X Yosemite.

> Xcode 6.3 - Build 6D520o
> https://developer.apple.com/xcode/downloads/

Sounds promising! I'll try and find some time to verify this on the latest beta build

**Comment by jasperblues** [comment] 2015-02-11 00:45
@mowens That's great news! Thanks so much for taking care of this. Hey would you like to be featured on the Typhoon website as a contributor? We add a picture and short-bio of folks who've made significant contributions.

**Comment by mowens** [comment] 2015-02-11 18:01
@jasperblues Sad news. I still received a crash on the release configuration. I wasn't able to debug too much into it last night but I will look into it in more detail shortly. Seems like there are some issues resolving symbols of release builds in Xcode Beta which was making it more difficult to determine if the crash point is the same as before or not. Anyways, I'll keep you posted.

As for being listed on the Typhoon website as a contributor, that sounds great :) I'd love to be featured. Thanks man!

**Comment by jasperblues** [comment] 2015-02-13 08:31
@mowens Damn, that's too bad. Hope its resolved soon. At least encouraging that its being given attention. 

Can you send us a pic and brief bio?

**Comment by mowens** [comment] 2015-02-19 05:39
@jasperblues GREAT NEWS! Swift 1.2 has fixed the release mode optimizations :+1: 

I finally had time to really look into the Swift 1.2 code in regards to the Typhoon-Swift project. Turns out the original crash in release mode for 1.2 was cased by some bad Swift code due to the 1.2 upgrade. 

I have created a branch with the updated code that now works great under 1.2 :) 

https://github.com/appsquickly/Typhoon-Swift-Example/tree/feature/swift-1.2

For parties that are interested there are 2 commits on this branch. The first commit just updates the Pod dependencies. The second commit contains the Swift 1.2 code changes. I am going to keep this as a feature branch until 1.2 is out of beta.

**Comment by jasperblues** [comment] 2015-02-19 05:45
@mowens AWESOME! Thanks so much for taking care of this.  

Swift + 💉💉💉💉💉💉 =  	🎉 	🎉 	🎉 	🎉 	🎉 	🎉

**Comment by mowens** [comment] 2015-02-19 06:48
@jasperblues No problem :+1: 

I sent you an email with my pic and bio from mike.owens11@gmail.com

**Comment by dereekb** [comment] 2015-02-28 20:38
I've run into a problem that I assume is linked to this and also only occurs in releases. Basically the wrong values are being injected and coming from absolutely random (but consistent) locations. For example, an inline string value was being replaced with a value from a TyphoonConfig instance.

**Comment by mowens** [comment] 2015-02-28 21:13
@dereekb could you post your code that is causing the issue?

**Comment by dereekb** [comment] 2015-03-01 02:49
There is nothing particularly special about it, and the project is bigger than I'd like to post.

The injection that messed up wasn't anything in particular:

```swift
    public dynamic func appContext() -> AnyObject {
        return TyphoonDefinition.withClass(VISAppContext.self) { ... }
   }

    public dynamic func destinationKeyAccessor() -> AnyObject {
        return TyphoonDefinition.withFactory(self.appContext(), selector: "makeKeyAccessorWithType:", parameters: { $0.injectParameterWith("destination") })
    }
```

I restructured this Typhoon definition multiple times, and the injected value was first consistently a string that was defined in a config, and then a CGRect that was defined inline in another injection for UIWindow, so I am pretty certain it was just Swift optimization bugs.

I'll try and reproduce it in another smaller app and post that here if you'd like to see it. I also have a lot of debug outputs that show the values being injected because I was going to bring up the issue here.

**Comment by jasperblues** [comment] 2015-07-11 11:19
I've been leaving this open for folks using Swift prior to version 1.2. I think we can close it soon.

**Closed** 2015-08-08 02:01 UTC
Labels: Apple Bug, ready-for-review, Show Stopper
