### ISSUE TITLE
Carthage Built Framework Missing File?

### ISSUE THREAD

**Issue by zenkimoto** [appsquickly/Typhoon#384] opened 2015-07-19 22:45 UTC
Hi Everyone,

I'm wondering if I'm doing something wrong.  I've built Typhoon.framework with Carthage, but when I add the built framework to my project and `import Typhoon`, I always get this error:  `'TyphoonFactoryDefinition.h' file not found`

I've tried specifying a lower version instead of 3.2.2.  I'm currently using 3.2.0 and I still get the same issue.

**Comment by jasperblues** [comment] 2015-07-19 22:48
investigating now. . .

**Comment by zenkimoto** [comment] 2015-07-19 22:51
Thanks @jasperblues 

I'm using currently using a Swift project too if that makes any difference.  I just cloned and opened up Typhoon and I don't see anything that jumps out at me too.

**Comment by jasperblues** [comment] 2015-07-19 22:55
According to StackOverflow: *"A quick fix (but not solving the root cause) is to set the following setting to yes: CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES"*

**Comment by zenkimoto** [comment] 2015-07-19 23:06
Hmm, I tried setting the build setting to YES, it's still giving me the same issue.  I also did a clean and build too.  I can switch back to Cocoapods if needed.  Not a big deal.

**Comment by jasperblues** [comment] 2015-07-20 10:19
@zenkimoto I'm closing this issue as it was reported by two people at the same time. (Thanks so much - better to be reported twice, then zero times). Please follow #383

**Closed by jasperblues** 2015-07-20 10:19 UTC
